### ISSUE TITLE
New Feature - Wallpaper

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#175]
To set bing wallpaper of the day as wallpaper.

**Comment by umangahuja1** [comment]
I have prepared the script just that I don't know how to set it run everyday at a specific time. Can anyone suggest ways.

**Comment by appi147** [comment]
cronjob

**Comment by umangahuja1** [comment]
I tried but it doesn't run on startup

**Comment by appi147** [comment]
It's difficult to add this functionality in a program. It will be better if it works as a single script. Otherwise, we can add commands such as change wallpaper to Jarvis

**Comment by umangahuja1** [comment]
Yeah we can change the wallpaper but we have to specify to change to what?

**Comment by umangahuja1** [comment]
What to do with this then?

**Comment by appi147** [comment]
If you have any idea or implementation, open a PR, or let any one come 

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
I wrote script that can manually change wallpic but not automatically.

**Comment by appi147** [comment]
Open a PR 

_Sent from my Xiaomi 2014818 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by umangahuja1** [comment]
https://github.com/umangahuja1/Scripting-and-Web-Scraping/blob/master/Wallpaper/bing.py.
I am not sending PR because tests are not passing yet.

**Comment by umangahuja1** [comment]
Hey @appi147 Can we do it like whenever we run Jarvis it runs this script. Can you mention a way to achieve the same?

**Comment by appi147** [comment]
I think there is initialization. Will look in evening

**Comment by appi147** [comment]
@umangahuja1 I could not think of any method. Is there any @sukeesh @StefanosChaliasos

**Comment by cyberboysumanjay** [comment]
We can also use Unsplash API for fetching wallpapers and for running the script automatically we can use systemd. It works fine on my Raspberry PI

**Comment by pnhofmann** [comment]
Perfectly ok with Unsplashed.

Just noticed there are two "APIs":
The big one: https://unsplash.com/developers
But it is also possible to get random images much simpler:
https://source.unsplash.com/

I would strongly recommend 2. option because it does not require API key!

About systemd, rather not. Systemd requires root + only works on linux - and actually not even on all linux systems. i Already implemented sort of really simple scheduler for remind-feature.

Biggest problem I see would be actually changing the wallpaper. Because I don't know a standardized way to do so for different Desktop environments (Gnome, KDE, xfce, ...).

**Comment by appi147** [comment]
Dont know if it can be done with only python, but it can be done with `feh` as much as i know

**Comment by pnhofmann** [comment]
Good point - `feh` is quite useful. Downsides: Does not survive reboot and does not work with Wayland.

**Comment by pnhofmann** [comment]
Closing this issue, because it's quite old and I honestly don't think it's worth the effort, because every Linux-desktop apparently needs different way to set wallpaper.

Additionally there are  [tools](https://www.omgubuntu.co.uk/2016/09/a-bing-wallpaper-linux-app-for-dummies) out there to change wallpaper e.g. to bing wallpaper of the day. 

But in case someone wants this feature and would like to implement it, feel free to re-open.
