### ISSUE TITLE
Add feature to display lyrics

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#183]

**Comment by StefanosChaliasos** [comment]
Here is an [API](https://pypi.python.org/pypi/PyLyrics/) we could use.

**Comment by jlvivero** [comment]
hey guys, I'm new here, I would like to work on this if it's alright with you guys.

Something I noticed is that the API @StefanosChaliasos  linked is not mantained anymore, and has a few errors, since making a fork just for this might be too much of a hassle so I'll probably just copy the methods needed and give credit to the owner.

**Comment by appi147** [comment]
@jlvivero welcome here. Feel free to use any API

**Comment by jlvivero** [comment]
Awesome, I already have a preview of the feature, but I am not too familiar with CI, so I don't know If I should just make a pull request and see if anything fails.

**Comment by umangahuja1** [comment]
Feel free to make a PR if anything happens we will discuss and sort it out.

**Comment by jlvivero** [comment]
#188 hope it's not too horrifying to read
