### ISSUE TITLE
Lyrics - help

### ISSUE THREAD

**Issue by umangahuja1** [sukeesh/Jarvis#250]
How is this feature exactly work?

**Comment by appi147** [comment]
@jlvivero Unfortunately this feature is currently not working. Can you fix it?

**Comment by jlvivero** [comment]
I'll check it out, I need to see what broke exactly, unfortunately the feature is dependent on third parties (like who serves the lyrics and the python library).

**Comment by umangahuja1** [comment]
If you need any sort of help let us know here.

**Comment by jlvivero** [comment]
sorry for the delays I had to lend my laptop to my brother because his broke. my linux enviroment is there which is where I test and do development for open source stuff. 

So I updated jarvis and I am having problems even installing the newer version, I had a dbus problem (which I solved by changing and if fi statement in the setup.sh which is a problem btw, and also removing the sudo from pip install dbus-python ).

that finally successfully installed it and when i run jarvis i get the following error:
![screenshot_20171117_093256](https://user-images.githubusercontent.com/7948154/32960596-5aa62d7a-cb7a-11e7-9a86-3ab7eb2193bb.png)

Any ideas? (I wish I had the old version to compare functionality so I could identify easily what broke but unfortunately i had to wipe my laptop after I got it back)

**Comment by appi147** [comment]
imdb package upgraded to python3 only

**Comment by jlvivero** [comment]
Should build again with python3 then?

**Comment by appi147** [comment]
Can you try `pip install IMDbPY==5.1.1` to test if works because it is already cached on my machine

**Comment by appi147** [comment]
@jlvivero

**Comment by 7ayushgupta** [comment]
Is this issue currently unassigned? I'd like to work on that issue. 
PS: I am a newbie to the codebase

**Comment by 7ayushgupta** [comment]
It's no problem. I'll work a bit on it on my own :smile:

**Comment by jlvivero** [comment]
@7ayushgupta I just got my internet back, how I'll setup my work environment tonight and if you need help or are having trouble doing it, I'll get on it on the weekend
