### ISSUE TITLE
Jarvis for windows

### ISSUE THREAD

**Issue by EhWhoAmI** [sukeesh/Jarvis#346]
Maybe I or someone could do a port to put jarvis on windows. Would be helpful.

You know,  create bat counterparts to the sh files, etc...

**Comment by appi147** [comment]
We are unfamiliar to windows systems, installation of modules, setting paths, etc. If you could it would be great. If you are willing to let us know.

**Comment by appi147** [comment]
Also will jarvis work from cmd?

**Comment by KrDimitrov** [comment]
Is this still open? Im currently working on a bat script to set up jarvis!

**Comment by pnhofmann** [comment]
Nice!
I noticed you deleted the setup.sh "we dont need it anymore hehe" - that would obviously not be acceptable. ;).
But apart from that: Would you mind creating a **pull request**?



Stuff - probably - needs to be done next:
- ``jarviscli/plugin.py`` - on top Constants MACOS and LINUX are decelerated. Should add WINDOWS
- ``jarviscli/PluginManager.py``: ``PluginDependency::__init__`` - set ``self._requirement_platform`` to ``plugin.WINDOWS``. So that we can create plugins exclusively for Linux/MacOS or Windows 
- ``jarviscli/utilities/notification.py`` shows small Desktop-notifications. This should receive implementation for Windows, too
- Some comments still may not work on Windows. Example: jarviscli/plugins/shutdown.py. (search for os.system - like already noticed). Those should be [disabled](https://github.com/KrDimitrov/Jarvis/blob/windows-port-stable/PLUGINS.md#require) or a Windows version implemented.

**Comment by pnhofmann** [comment]
Created new branch [windows port](https://github.com/sukeesh/Jarvis/tree/windows-port) for further development.

**Comment by EhWhoAmI** [comment]
I tried the port out on windows and it comes out a little messy. I think the curses are not parsing it well. 
![example](https://user-images.githubusercontent.com/22135886/52684668-9d7f7600-2f0c-11e9-9e4b-6d3203eb6eeb.png)

**Comment by pnhofmann** [comment]
Yes, windows port is in an early stage. According to [stackoverflow](https://stackoverflow.com/questions/8358533/python-module-to-enable-ansi-colors-for-stdout-on-windows) we just need to call ``colorama.init()`` somewhere.
I've pushed a patch 65123f2d6080a2e91c36835a40764d1998e1572b but I was too lacy to test on a windows machine ;). Could you check if it worked as expected?
It is still somewhere on my list to give windows port bit more love ;). But first I want to finish my other stuff (review plugin architecture + tests).
And of course any help with windows port is still welcome ;).

**Comment by KrDimitrov** [comment]
Tested windows-port branch. 

![image](https://user-images.githubusercontent.com/29924708/52703037-ba07c680-2f7d-11e9-82fc-957d60930afe.png)

Looks like only these two lines are not working properly. I remember trying to fix it a while ago but couldn't.

**Comment by EhWhoAmI** [comment]
What are the colors supposed to be?

**Comment by EhWhoAmI** [comment]
Looks like the colors 39 do not exist according to the ansi codes reference (<https://bluesock.org/~willkg/dev/ansi.html>), but 31 should be red. Maybe it did not put the ending code properly?

**Comment by pnhofmann** [comment]
At last an improvement ;). But this is a quite interesting issue. 39 is [Default foreground color](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters). And does [seem](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) like this **is** implemented in Windows.

Also the red from "I could not identify your command" is the **same** red as from "Hi, what can I do for you?". Both times Fore.RED is used. Funny, this works one time and one time doesn't.

I'll probably do need an Windows VM - I'll investigate this issue and report back later.

**Comment by pnhofmann** [comment]
For some reason, python input() with colors do not work on Windows CMD. **Should be fixed now.**
I rewrote relevant parts so input() isn't used any more (directely write / read from sys.stdout / sys.stdin).

**Comment by appi147** [comment]
merging #536 , renamed to bare bones for windows
Will add new pr for full windows capabilities,
did not change readme(win is beta for now)

**Comment by appi147** [comment]
#561
