### ISSUE TITLE
fix news command

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#36]

**Comment by bwh91** [comment]
Do you have any insight on this? @StefanosChaliasos does the news functionality need to be redesigned?

**Comment by StefanosChaliasos** [comment]
![screenshot from 2017-03-30 22-31-20](https://cloud.githubusercontent.com/assets/15054312/24522803/6512cfda-1599-11e7-8a55-58c6b24b5e7a.png)
That happens if we remove the try statements in news method. I think we must solve this bug

**Comment by bwh91** [comment]
I think we may need to come up with another solution. Instead of grabbing the content from news.google.com why not change this to work with the Bing news API? That way it will be a standard way to get the news content and I think it will work better than parsing the news.google page. Here is a link to the bing API [https://msdn.microsoft.com/en-us/library/dn760783.aspx](url)

**Comment by StefanosChaliasos** [comment]
Good idea can you work on it?

**Comment by bwh91** [comment]
Yeah, I will work on this next.

**Comment by StefanosChaliasos** [comment]
#65

**Comment by jsgtihub** [comment]
When entering the news command

news

I get

"Would you like to configure your own news source? (yes/no):
I typed "n" for no.

It then shoots back the command "Would you like news from this news source? (yes/no):
I typed "n" for no.

Select Source
1. BBC
2. BUZZFEED
3. Google
4. Reddit
5. TechCrunch

I typed "3" for Google.

Would you like to set this up as your default? (yes/no):
y

"I couldn't find news."
