### ISSUE TITLE
News site listed under News plugin has to be configurable.

### ISSUE THREAD

**Issue by jay4563** [sukeesh/Jarvis#402]
Instead of having static option for the sites, it will be good to have option to configure the required site as per one's interest. Since newsapi supports multiple websites, it will be good to have option to have list of sites of their interest.

**Comment by jay4563** [comment]
I would like to contribute for this enhancement if you guys are ok with it.

**Comment by pnhofmann** [comment]
> I would like to contribute for this enhancement if you guys are ok with it.

Of course!

**Comment by pnhofmann** [comment]
And please ask if you have any questions / problems. My description of how to create plugins is currently not what I would like it to be (working on it ;) ). Because also I noticed, this isn't documented anywhere: Note that Jarvis has the methods add_date, get_data, update_data and del_data to store data ;).

**Comment by jay4563** [comment]
Thanks @pnhofmann.  If someone can share, what is the development workflow then it will be easy for me to follow the steps.

**Comment by pnhofmann** [comment]
> what is the development workflow

There is actually nothing special. Just the generic:

* Fork + Clone
* create branch (z.B.: git checkout -b news_configuration)
* Code
* Check that ./test.sh does not yield any errors
* commit
* push
* Press the "Create Pull Request" button on github

;).

**Comment by pnhofmann** [comment]
#407
