### ISSUE TITLE
Stuck on Centos 7

### ISSUE THREAD

**Issue by Tobe-Continued** [sukeesh/Jarvis#412]
I want install it on my home server in CentOS 7 , but in your file setup.sh it try to installdependencies with "apt-get" but in centos it's "yum".

**Comment by pnhofmann** [comment]
Thank you for reporting this issue!

This is really interesting - what's the content of your ``/etc/os-release``? Actually apt-get is only used if ID_LIKE contains 'debian'.

This is probably about the new voice control feature, which does require Portaudio, because we (currently) have no other way for recording audio. If you don't need voice control, you won't need to install portaudio. If the setup.sh script does fail, your options are to either install portaudio + python binding manually or use Jarvis without voice control. I'll update setup.sh to make this clearer.

Nevertheless, can't imagine why apt-get is called on CentOS. Could you post the output of setup.sh?
