### ISSUE TITLE
Music Playback Issue

### ISSUE THREAD

**Issue by jsgtihub** [sukeesh/Jarvis#415]
When entering the input music I get the following message.
Song name doesn't exist. ( play 'song name' )

**Comment by pnhofmann** [comment]
This message is somehow misleading.

You didn't specify a song name - e.g. ``music wonderful tonight``.  Therefore the song name does not exist - not because of a error but just because none was specified ;). Should probably be updated to something like: "You didn't specify a song name" or "Please add a song name" to avoid confusion.
