### ISSUE TITLE
PyAudio error

### ISSUE THREAD

**Issue by JonanOribe** [sukeesh/Jarvis#443]
I found a problem when I tried to install Jarvis using ./setup. Looks like the pyaudio packages can't be install. Any idea?? I tried with "sudo pip install python-pyaudio" but at the end I have the same error.

Command "/Jarvis/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xlaun6vd/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/usr/local/include -L/usr/local/lib install --record /tmp/pip-record-7j7flc8j/install-record.txt --single-version-externally-managed --compile --install-headers Jarvis/env/include/site/python3.6/pyaudio" failed with error code 1 in /tmp/pip-install-xlaun6vd/pyaudio/

**Comment by pnhofmann** [comment]
Hi!

could you post complete output of Jarvis setup.sh? Because acutally it should print something like:

```
.11.tar.gz
Skipping bdist_wheel for pyaudio, due to binaries being disabled for it.
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command /home/phil/git/Jarvis/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_lf0z1zb/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/usr/local/include -L/usr/local/lib install --record /tmp/pip-record-npg_w5x2/install-record.txt --single-version-externally-managed --compile --install-headers /home/phil/git/Jarvis/env/include/site/python3.7/pyaudio:
    running build_ext
    building '_portaudio' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/local/include -I/usr/include/python3.7m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.7/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory
     #include "portaudio.h"
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Portaudio is required for voice control. On your system, it can be installed using:
> sudo zypper install python3-PyAudio
```

I could also try to make the output more clearer, that:

* pyaudio is completely **optional** and only required for (early version of) voice recognition 
* pyaudio **must** be installed with the package management system of your os. Does require native extension - not "nice" but currently our only way

**Comment by JonanOribe** [comment]
Thanks for your fast response. I think that probably this will be something with my SO, because sometimes  it gives me problems with the dependencies without any reason.I will try this way

**Comment by JonanOribe** [comment]
Finally, I achieved to install PyAudio. The steps were:

-pip install --upgrade setuptools
-sudo apt-get install portaudio19-dev
-sudo apt-get upgrade
- sudo apt-get update
-sudo  pip install PyAudio

I hope this will help anyone who find the same problem

**Comment by anthonyvluc** [comment]
If you are on Mac, you can run
`brew install portaudio`

**Comment by anthonyvluc** [comment]
Actually, I just noticed an error in the `installpyaudio.py` file. Line 30 needs to change from `elif platform.system().lower() == "Darwin":` to `elif platform.system().lower() == "darwin":`. That was why I had to run the brew command manually.

How do I go about making/suggesting this change to the `setup.sh` script?

**Comment by JonanOribe** [comment]
> If you are on Mac, you can run
> `brew install portaudio`

Thanks for the advice, but I´m on an Ubuntu 18.04. Good catch with that bug ;)

**Comment by steeve-legal** [comment]
I have a similar problem on ubuntu 18.04, tried JonanOribe code, still getting this error message,
Any help will be much appreciated
  Running setup.py install for pyaudio ... error
Portaudio is required for voice control. On your system, it can be installed using:
> sudo apt install python3-pyaudio
Install now? (y/n)y
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
python3-pyaudio est déjà la version la plus récente (0.2.11-1build2).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
/home/steeve/Jarvis/env/lib/python3.6/site-packages/pip/_internal/req/req_file.py:185: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options, opts)
Requirement already up-to-date: SpeechRecognition in ./env/lib/python3.6/site-packages (from -r requirements_voice_control.txt (line 1)) (3.6.1)
Collecting pyaudio (from -r requirements_voice_control.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Skipping bdist_wheel for pyaudio, due to binaries being disabled for it.
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /home/steeve/Jarvis/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fz84vr1b/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fz84vr1b/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext -I/usr/local/include -L/usr/local/lib install --record /tmp/pip-record-36yhzyzf/install-record.txt --single-version-externally-managed --compile --install-headers /home/steeve/Jarvis/env/include/site/python3.6/pyaudio
         cwd: /tmp/pip-install-fz84vr1b/pyaudio/
    Complete output (11 lines):
    running build_ext
    building '_portaudio' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.6m -I/home/steeve/Jarvis/env/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
    src/_portaudiomodule.c:28:10: fatal error: Python.h: Aucun fichier ou dossier de ce type
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/steeve/Jarvis/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fz84vr1b/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fz84vr1b/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext -I/usr/local/include -L/usr/local/lib install --record /tmp/pip-record-36yhzyzf/install-record.txt --single-version-externally-managed --compile --install-headers /home/steeve/Jarvis/env/include/site/python3.6/pyaudio Check the logs for full command output.
steeve@steeve-HP-Pavilion-dv7-Notebook-PC:~/Jarvis$

**Comment by pnhofmann** [comment]
Hi!

You can safely ignore this error - if you don't plan to use voice recognition (which is in an early stage anyway).

To fix this error you would need to:

``sudo apt-get install python-dev``

for Python 2 or for Python 3: 

``sudo apt-get install python3-dev``

I'll merge updated installer soon, which will improve output.

**Comment by steeve-legal** [comment]
Thanks for your quick reply,
python-dev and python3-dev were already installed on my system...
Do I have to set it up in one of Jarvis folder and if yes how ?
I'm working on this with a very small team to set an ubuntu system able to be used by disable people like nearly blind or blind and other disabilities, voice recognition would be greatly useful with French language added with original English.
Anyway this is the best work on Jarvis I've seen ever done
Best regards, looking forward for your new installer !

**Comment by pnhofmann** [comment]
> python-dev and python3-dev were already installed on my system...

That's strange. This Python.h should definitly be included in python3-dev. Currently no idea - Sorry...

> Anyway this is the best work on Jarvis I've seen ever done

Thanks ;) - but

> I'm working on this with a very small team to set an ubuntu system able to be used by disable people like nearly blind or blind and other disabilities, voice recognition would be greatly useful with French language added with original English.

This is basically a playground for beginners (including me) to learn basics of development. And of course to have fun with a software, which can actually be quite useful for personal use.

I'm really sorry, but I don't think this project is ready for your use-case. Especially since Voice recognition is really something, where we only added some really basic lines to integrate the google api - so please don't expect much.

Still, wish you the best for your project!

**Comment by steeve-legal** [comment]
Thanks for this detail about this Python.h, I'll try on my side but I don't hope since I've tried so many assistants without any good results excepted your one working very well with text typing.
I guess that might be possible one day or not.

Wish you the best too !

**Comment by steeve-legal** [comment]
I just found  2 Python.h files located in /usr/include/python3.6m and /usr/include/python2.7
P for Python.h in uppercase, could it be a path problem ?

Cordially

**Comment by steeve-legal** [comment]
Hello, couldn't let it like this, I apologize, everything went well with python-dev and python3-dev, I just forgot to restart python after that.
Then I've been able to install Jarvis with none error
Thanks for the trick !

**Comment by pablorq** [comment]
Hi,

On Ubuntu 19.04 I confirm the following is needed to install pyaudio:

`sudo apt-get install portaudio19-dev`

And the following is for hear jarvis talking:

`sudo apt-get install espeak`

Enjoy!
