### ISSUE TITLE
Make require for windows

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#531]
Windows does not seem to respect @require(linux)

**Comment by appi147** [comment]
@pnhofmann Any ideas

**Comment by pnhofmann** [comment]
Yep, isn't implemented yet - like documented here:
https://github.com/sukeesh/Jarvis/issues/346#issuecomment-431596464
And unfortunately nothing has changed since ;(.

The @require(linux) check just wasn't build with windows in mind - basically checks if system is not macOS... Should be quite easy to fix.

**Comment by appi147** [comment]
Thank you

**Comment by pnhofmann** [comment]
I would also introduce require(platform=UNIX) as shortcut for Linux or MacOS.

What should we do about cygwin? Is this Windows or Linux or unix or a own platform or not supported?

**Comment by appi147** [comment]
With arrival of Linux subsystem on Windows, cygwin is kinda not required to support. I am not interested in supporting cygwin. Maybe let it be unsupported.

UNIX is a good idea.

methods such as shutdown, or commands like sudo, grep, can be moved in UNIX.

**Comment by appi147** [comment]
For python2.7.3+ [Possible outputs of sys.platform](https://docs.python.org/2/library/sys.html#sys.platform). Main point linux2 is used for most Linux systems.
For python3.3+ [Possible outputs of sys.platform](https://docs.python.org/3/library/sys.html#sys.platform). Main point linux is used for all linux systems
