### ISSUE TITLE
Plugin categories

### ISSUE THREAD

**Issue by Dastar** [sukeesh/Jarvis#551]
There are four different plugins to generate something random (coin, dice, random_number and random_password) and already two different games (cows and bulls and rockpaperscissors).

Maybe I should organise them into one plugin (one fir random, second for games), and from this plugins we will call specific plugins?

**Comment by pnhofmann** [comment]
There is e.g. already plugin 'random' with subcommands 'number' and 'password'.

That's because if you create a plugin "random password", actually two plugins are crated: "random" and "password" as sub-plugin of random.

What I agree:

* We could add "random_coin" and "random_dice" as aliac for "coin" and "random" (without problem)
* We could add "game_bulls" and "game_rockpaperscissors" as alias for "bulls" and "rockpaperscissors" (without problem)
* Maybe we could also rewrite e.g. help page to represent this "categories" (bit complicated)

**Comment by aazuspan** [comment]
> * Maybe we could also rewrite e.g. help page to represent this "categories" (bit complicated)

@pnhofmann It might be worth considering migrating from cmd to cmd2 to achieve this. Cmd2 has command categories built in: https://cmd2.readthedocs.io/en/latest/features/help.html#categorizing-commands

**Comment by pnhofmann** [comment]
Now tracked here: #887
