### ISSUE TITLE
Installation problem on ubuntu 18.04

### ISSUE THREAD

**Issue by jay24rajput** [sukeesh/Jarvis#593]
> ============== Preparing virtualenv ==============
> Shell: virtualenv env --python=python3; run_in_virtualenv: False
> Shell: Exit ok
> #################################
> 
> 
> Already using interpreter /usr/bin/python3
> Using base prefix '/usr'
> New python executable in /home/jay/Jarvis/env/bin/python3
> Also creating executable in /home/jay/Jarvis/env/bin/python
> Installing setuptools, pkg_resources, pip, wheel...done.
> 
> 
> ============== Install requirements ==============
> Shell: pip install -U -r installer/requirements.txt; run_in_virtualenv: True
> Shell: Exit fail
> #################################
> 
> 
> 
> Installation failed
> 
> FATAL!

The following log file is generated after running ```python installer```. Any solutions?

**Comment by pnhofmann** [comment]
Thanks for reporting this bug!

Did some research - this should be caused by trouble with ``source env/bin/activate`` in non-interactive shell and found a workaround. But need to do some more testing + make my fix work on windows => On my list for tomorrow ;).

For now, you can use this fix I uploaded to my personal branch:

https://github.com/pnhofmann/Jarvis/tree/installer

At last worked for my 18.04 VM.

**Comment by alexandr7035** [comment]
+

**Comment by pnhofmann** [comment]
Fixed!
