### ISSUE TITLE
New Feature- Open Browsers through Jarvis for more precise searching

### ISSUE THREAD

**Issue by akshgpt7** [sukeesh/Jarvis#606]
There are a lot of things that you won't be able to search through the command line directly. So, a command to open browser windows directly through Jarvis would make it more interesting altogether.

**Comment by pnhofmann** [comment]
Hi!

* There's open website (Just noticed: Currently broken ;( => I'll push a fix later.)
* There is google (Soon ;) => #605)

If I correctly understand, what you want is something like an extension for ``google``:

* Google in webbrowser

Which instead of printing short summary opens webbrowser on google? This would be a nice plugin. You would like to implement it?

**Comment by akshgpt7** [comment]
Yes, you got it right. I'll work on the command ```open browser``` .

**Comment by pnhofmann** [comment]
#616
