### ISSUE TITLE
Jarvis graphic user interface

### ISSUE THREAD

**Issue by Baocaifeng** [sukeesh/Jarvis#638]
hello, I want to add a new plugin gui (graphic user interface)

**Comment by pnhofmann** [comment]
Hmm, there's already #493 / #421 (but haven't heard anything new for a while) and #526 (don't know if something happens there, too).

This is a quite open project; if anyone has a working GUI and find this GUI useful, we will merge for sure.

But just to link related topics.

**Comment by arjunk2004** [comment]
Do you think it's a good idea to use zenity, at least for Ubuntu installations?

**Comment by pnhofmann** [comment]
Zenity would be easy to integrate - but of course restricted in what's possible, since zenity is no full GUI framework.

Currently I'm experimenting with [kivy](https://kivy.org/). Main advantage: Cross Platform and can even be ported to Android / iOS with minimal effort.

However closing this issue as duplicated: #421
