### ISSUE TITLE
New feature - Enable command history and self - completion

### ISSUE THREAD

**Issue by gkodosis** [sukeesh/Jarvis#678]
Hello there, I hope you are doing great and staying safe! 
I was thinking about upgrading the jarvis cli, by adding an up/down arrow key parsing of the commands used by a user, as well as a simple self - completion of the command (using the tab key). 
Let me know if you find it usefull, so that I can work on it!

**Comment by pnhofmann** [comment]
Hi!

yeah, you are absolutely right! This is something, I should have taken a closer look for some time.

But you'll probably be surprised, how easy this feature is to implement - it's literally a one-liner, since there is readline: 
https://docs.python.org/3/library/readline.html

Readline made some problems on windows, but yeah let's activate readline at last for Unix.

```
diff --git a/jarviscli/Jarvis.py b/jarviscli/Jarvis.py
index 8480f0c..8d3c611 100644
--- a/jarviscli/Jarvis.py
+++ b/jarviscli/Jarvis.py
@@ -1,6 +1,6 @@
 # -*- coding: utf-8 -*-
 
-import os
+import os, sys
 from colorama import Fore
 import nltk
 import re
@@ -49,7 +49,8 @@ class Jarvis(CmdInterpreter, object):
                  prompt=prompt, first_reaction=True,
                  directories=["jarviscli/plugins", "custom"]):
         directories = self._rel_path_fix(directories)
-        self.use_rawinput = False
+        if sys.platform == 'win32':
+            self.use_rawinput = False
         self.regex_dot = re.compile('\\.(?!\\w)')
         CmdInterpreter.__init__(self, first_reaction_text, prompt,
                                 directories, first_reaction)
```

Plus add readline to installer (would do this, because needs to be an optional feature since requires non-python extension).

> Let me know if you find it usefull, so that I can work on it!

So would could you do, if you like?

* You could add more features. E.g. persistent history just like .bash_history would be nice. Or add more shortcuts. And so on.
* Or you could check, if there is an alternative, that does not depend on readline

**Comment by gkodosis** [comment]
> * Or you could check, if there is an alternative, that does not depend on readline

You are absolutely right, it was readline module that I had on my mind. Inspite of including readline as an optional non-python requirement, I came up with a middle solution: tempfile; a module which with the correct set up works pretty well in both Linux and Windows! Nevertheless, tab-completion works really well as is, providing users with shortcuts to plugins (so, I didn't want to alter this feature).

> * You could add more features. E.g. persistent history just like .bash_history would be nice. Or add more shortcuts. And so on.

So, I added a plugin executable by: **cat his**, which provides you with the commands you typed during the session (mirroring .bash_history, but without keeping your entire history of commands, cause it didn't seem so practical and usefull)

Hope you agree with me and my concerns :sweat_smile:
