### ISSUE TITLE
Error in translate plugin

### ISSUE THREAD

**Issue by nikiboura** [sukeesh/Jarvis#868]
Hello! 

Me and @IriannaPapoutsi  tried to use translate plugin but when we entered the input text an error occured, regardless the input languages, as you can see bellow.

![204527625_945505632910682_7343664393504555310_n](https://user-images.githubusercontent.com/56998869/122827699-5cbe7580-d2ed-11eb-8b34-ede456d7e3a1.png)

![204571788_324726815784345_3726785984003915878_n](https://user-images.githubusercontent.com/56998869/122827705-5f20cf80-d2ed-11eb-9efc-c7a86bde0cf5.png)

**Comment by pnhofmann** [comment]
Hi!
seems to be an issue with py-googletrans - which is fixed in dev version googletrans==3.1.0a0.
I just updated requirements.txt
https://github.com/sukeesh/Jarvis/commit/691f1f2927419c45886a99305ab0a9797fd084a1

If you ``git update`` and re-run installer, this should be fixed (if not, please re-open ;) ).
