### ISSUE TITLE
dev -> master When to merge ?

### ISSUE THREAD

**Issue by antiDigest** [sukeesh/Jarvis#871]
Maybe we can discuss here when it would be appropriate to merge the dev branch to master.

I'm thinking:
- we can stop any merges to master, make master the main branch (which it already is) and only allow new plugins to dev. Maybe even organize new additions. Like every new plugin requires a unit test or something to be able to merge. (Maybe more of a long term plan here, but I think you get my point.)
- But in the current scenario, I would suggest pausing all merges to master, and making dev the open branch to merge into. Reason being, master is already too different from dev, I think. Until we figure out how to make those same, better to keep merging open only to dev.

Thoughts @pnhofmann. We can tag other collaborators for more thoughts as well.

**Comment by Martins6** [comment]
Maybe I'm snooping where only senior contributors are welcome, but, if I may...just to add that the dev-branch has some awesome features, in my opinion, that the master branch would love to have! The sooner those features become the standard, the better!

Also, the feature of the marketplace (which is already in the dev-branch) could help to bring some order. One suggestion would be that the dev and master branch would only have essential builds, like speech module, etc. And, every minor improvement of feature would be suggested to have its own Github repo. That would also help with those features that have license impediment, since the Jarvis wouldn't directly supervise it and would be up to the owner to administrate such installments (or buys in the marketplace).

**Comment by pnhofmann** [comment]
Yeah, merge dev is really overdue. Next month I should have some time (I'd like to do some improvements on voice control). Then I would suggest, merge in August?

> Reason being, master is already too different from dev, I think.

Yes, I'll take care of the diffs - I don't think that's a major problem. I would suggest, handle master and if dev is ready to merge, I'll just "backport" everything on master ;).

**Comment by pnhofmann** [comment]
I'm late. But it's still August ;)

A preview what I did so far: https://github.com/pnhofmann/Jarvis/commits/dev

OK, now everything I decided I want to change is implemented. But I know: Lots of stuff is still a bit broken. So I'll do testing the next days. Guess, I'll need ~2 weeks and then I'll write again.

**Comment by Milind220** [comment]
What's going on with this? Was dev originally planned to be the branch that all PR's would be  made to and master would have the stable release?

**Comment by pnhofmann** [comment]
Hi @Milind220 
dev started with me experimenting stuff, but got lots of - I think - really interesting features. I consider it the next "release" of Jarvis.
And yes, it should really been merged by now. Sorry - I currently have unexpectedly lots of stuff "around". But sometime dev will be ready ;).

Maybe, if you do stuff like in #913 (any improvements really appreciated ;) ) - consider switching to dev ;).

**Comment by pnhofmann** [comment]
> dev -> master When to merge ?

Soon
