### ISSUE TITLE
Errors when running source setup.sh

### ISSUE THREAD

**Issue by edricantoine** [sukeesh/Jarvis#933]
I am unfortunately running into another issue now. Running python3 installer works now, but when I try to run source setup.sh as advised in the readme for mac users, I am getting this error:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/72291309/156816397-e476ff11-f28b-429a-9257-c7cd3614b83e.png">

Seems to be a simple syntax error, though... I'll see if I can possibly try to fix it.

Update: Upon reinstalling jarvis, I did not need to run source setup.sh, so is that still actually a requirement?

**Comment by edricantoine** [comment]
Also, from what I can tell messing around in a forked copy of the repository, the formatted print statements are giving me a hard time... the syntax errors don't show up when I remove the f's at the beginning of the print statement.

**Comment by pnhofmann** [comment]
> I think this may be because running source setup.sh runs the command python installer (which I am assuming uses python2) , while formatted python strings are a python3 thing.

You are absolutely right!

We haven't thought about this issue since Jarvis is Python3 only. But yeah, it is a good idea to keep the installer python 2 compatible, since we don't know how the installer is ran (and it really isn't much effort).

> Update: Upon reinstalling jarvis, I did not need to run source setup.sh, so is that still actually a requirement?

``setup.sh`` just calls ``python installer``. It was added for convenience - but yeah, it somehow got duplicated in README. So yes, we should remove the two lines:

```
On Mac OS X run source setup.sh

On Windows run setup.bat
```

**Comment by edricantoine** [comment]
Ok, I'll get working on that, in addition to the new plugin I opened an issue about earlier.

**Comment by pnhofmann** [comment]
#953
